# Generated by Django 3.2.12 on 2022-02-05 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Список электронных адресов',
                'verbose_name_plural': 'Список электронных адресов',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=150, null=True)),
                ('last_name', models.CharField(default='', max_length=150, null=True)),
                ('phone', models.CharField(default='', max_length=150, null=True)),
                ('email', models.CharField(default='', max_length=150, null=True)),
                ('avatar', models.ImageField(blank=True, default='media/avatars/orange.jpg', null=True, upload_to='media/avatars/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_header', models.CharField(max_length=500, verbose_name='Заголовок адреса доставки')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('notification_on_email', models.BooleanField(default=True, verbose_name='Получать уведомления по Email')),
                ('name_first', models.CharField(blank=True, default='', max_length=500, verbose_name='Имя')),
                ('name_last', models.CharField(blank=True, default='', max_length=500, verbose_name='Фамилия')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('country', models.CharField(max_length=500, verbose_name='Страна')),
                ('state', models.CharField(max_length=500, verbose_name='Штат/Регион')),
                ('zip', models.CharField(blank=True, max_length=10, verbose_name='Индекс')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('sub_phone', models.CharField(blank=True, max_length=20, verbose_name='Дополнительный номер телефона')),
                ('comment', models.TextField(blank=True, verbose_name='Дополнительный комментарий к доставке')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставки',
                'unique_together': {('user', 'address_header')},
            },
        ),
    ]
