# Generated by Django 3.2.12 on 2022-02-05 11:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=150, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='Заголовок')),
                ('title_de', models.CharField(max_length=150, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание')),
                ('description_ru', models.TextField(max_length=5000, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(max_length=5000, null=True, verbose_name='Описание')),
                ('description_de', models.TextField(max_length=5000, null=True, verbose_name='Описание')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('time', models.TimeField(auto_now=True, null=True, verbose_name='Время создания')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('poster', models.ImageField(null=True, upload_to='media/poster/', verbose_name='Постер')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Новость или событие',
                'verbose_name_plural': 'Новости и события',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1500, verbose_name='Коментарий')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('news', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.news')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Blog.comment', verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
