# Generated by Django 3.2.12 on 2022-02-05 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Interactive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название бренда')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('image', models.ImageField(upload_to='media/brands/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Card_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_public_ID', models.IntegerField(default=1111111, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=5000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('availability', models.BooleanField(default=True, verbose_name='hidden')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='На складе')),
                ('condition', models.CharField(choices=[('new', 'new'), ('fresh', 'fresh'), ('hand', 'hand')], default='fresh', max_length=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/product_icon', verbose_name='Изображение в корзине')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.brand', verbose_name='бренды')),
            ],
            options={
                'verbose_name': 'Карточка продукта',
                'verbose_name_plural': 'Карточки продуктов',
                'ordering': ['product_public_ID'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, max_length=1500, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='RatingGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(default=3, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Отображаемое значение рейтинга',
                'verbose_name_plural': 'Отображаемые значения рейтинга',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('ipaddress', models.CharField(max_length=15, verbose_name='IP адрес')),
                ('grade', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.ratinggrade', verbose_name='оценка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.card_product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Фотография товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.card_product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Фотография к товару',
                'verbose_name_plural': 'Фотографии к товару',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('name_first', models.CharField(max_length=350, verbose_name='Имя')),
                ('name_last', models.CharField(max_length=350, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('order_start', models.DateTimeField(auto_now_add=True, verbose_name='Получен')),
                ('order_finish', models.BooleanField(default=False, verbose_name='Исполнен')),
                ('status', models.CharField(choices=[('created', 'Заказ получен'), ('in_progress', 'Заказ обрабатывается'), ('ready_to_receive', 'Заказ готов к выдаче'), ('completed', 'Заказ исполнен')], default='created', max_length=22, verbose_name='Статус заказа')),
                ('buying_type', models.CharField(choices=[('self', 'Самовывоз'), ('delivery', 'Доставка')], default='self', max_length=22, verbose_name='Тип заказа')),
                ('cards', models.ManyToManyField(to='Shop.Card_Product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='DefaultDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Interactive.delivery')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Адрес по умолчанию',
                'verbose_name_plural': 'Адреса по умолчанию',
            },
        ),
        migrations.AddField(
            model_name='card_product',
            name='category',
            field=models.ManyToManyField(to='Shop.Category', verbose_name='категории'),
        ),
        migrations.CreateModel(
            name='BuyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveSmallIntegerField()),
                ('product_for_buy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.card_product', verbose_name='Купленные продукты')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.card_product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
                'unique_together': {('user', 'products')},
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.card_product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
